version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - MEDIA_ROOT=/app/media
      - MEDIA_URL=/media/
      - STATIC_ROOT=/app/static
      - STATIC_URL=/static/
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-land_use_db}
      - POSTGRES_USER=${POSTGRES_USER:-land_use_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-land_use_password}

volumes:
  postgres_data:
  media_volume:
  static_volume: 